-- Migration: Add Updated_At column to Orders if missing
-- Date: 2026-05-27
-- Adds `Updated_At` TIMESTAMP with ON UPDATE CURRENT_TIMESTAMP

-- Check current definition
SELECT COLUMN_NAME, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Orders'
  AND COLUMN_NAME = 'Updated_At';

-- Add column if it does not exist (MySQL 8+ supports IF NOT EXISTS)
ALTER TABLE Orders
  ADD COLUMN IF NOT EXISTS Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Verify
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Orders'
  AND COLUMN_NAME = 'Updated_At';
